# Welcome to Jekyll!
#
# About Theme
#
# Yet another theme for elegant writers with modern flat style and beautiful
# night/dark mode.
#
# Website: https://github.com/jeffreytse/jekyll-theme-yat
#
# You can do anything you want, including projects for your clients, as long
# as you mention an attribution back (credit links in footer or project).
# See the LICENCE file.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you
# use 'bundle exec jekyll serve'. If you change this file, please restart
# the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Max的博客
email: z_max_y@163.com
author: StreakingMan
copyright: Copyright © 2020-2021
description: >- # this means to ignore newlines until "baseurl:"
  裸奔狂甩丁丁的博客，记录各种花里胡哨的东西（前端、游戏设计、创意、随笔）。
  StreakingMan-Max-s github page blog about all kinds of awesome things, includes fed coding, game design, idea and so on.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/favicon.ico" # the favicon for your site

# Yat date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%b %d, %Y"

# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
# header_transparent: true

# Google analytics
# google_analytics: [Tracking ID]

# If you want to generate website sitemap, you can set true
sitemap: true

# If you want to change site language, you can set lang option
lang: "zh-CN"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: zh-CN
    img: https://www.countryflags.io/cn/flat/64.png
    text: 简体中文

  - lang: en
    img: https://www.countryflags.io/us/flat/64.png
    text: English

  - lang: fr
    img: https://www.countryflags.io/fr/flat/64.png
    text: Franch

  - lang: ja
    img: https://www.countryflags.io/jp/flat/64.png
    text: Japan

  - lang: ko
    img: https://www.countryflags.io/kr/flat/64.png
    text: Korean

  - lang: ru
    img: https://www.countryflags.io/ru/flat/64.png
    text: Russia

# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for always on/off.
# night_mode: "auto"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html
#   - about.md

# Page default value
defaults:
  home:
    heading: "StreakingMan"
    subheading: "种一棵树，最好的时间是十年前，其次是现在"
    banner: "Your image url"

# Pagination setting
# paginate: 5

# Disqus comments
# disqus:
#   shortname: "Your Disqus username"

# Gitment comments
gitment:
  username: "StreakingMan"
  repo: "streakingman.github.io"
  client_id: "0f6ccb61614db36eb8e3"
  client_secret: "e4e8de79bceda034bb3528aa49ce5788c1dc5926"
  redirect_uri: "https://streakingman.github.io/"   # If you use a custom domain name

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
